#!/usr/bin/env python3
import os
import sys
import struct

def strip_png(data):
    """Strip ancillary metadata chunks from PNGs, keeping only critical chunks."""
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        return data
    out = b"\x89PNG\r\n\x1a\n"
    pos = 8
    while pos < len(data):
        if pos + 12 > len(data):
            break
        length = struct.unpack(">I", data[pos:pos+4])[0]
        chunk_type = data[pos+4:pos+8]
        chunk = data[pos:pos+12+length]
        pos += 12 + length
        # Keep critical image chunks + transparency
        if chunk_type in [b"IHDR", b"PLTE", b"IDAT", b"IEND", b"tRNS"]:
            out += chunk
    return out

def main():
    repo_root = os.path.dirname(os.path.abspath(__file__))
    src_png = os.path.join(repo_root, "tdewin_128_16.png")
    
    if not os.path.exists(src_png):
        print(f"Error: tdewin_128_16.png not found in {repo_root}")
        sys.exit(1)

    with open(src_png, "rb") as f:
        raw_data = f.read()

    clean_data = strip_png(raw_data)
    out_header = os.path.join(repo_root, "config", "q4win10_logo.h")

    lines = []
    lines.append("/* Auto-generated by convert_images.py - DO NOT EDIT */")
    lines.append("#ifndef Q4WIN10_LOGO_H")
    lines.append("#define Q4WIN10_LOGO_H")
    lines.append("")
    lines.append(f"static const unsigned char q4win10_logo_png[{len(clean_data)}] = {{")

    for i in range(0, len(clean_data), 16):
        chunk = clean_data[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(clean_data) else ""
        lines.append(f"    {hex_str}{comma}")

    lines.append("};")
    lines.append(f"static const unsigned int q4win10_logo_png_len = {len(clean_data)};")
    lines.append("")
    lines.append("#endif // Q4WIN10_LOGO_H")
    lines.append("")

    with open(out_header, "w") as f:
        f.write("\n".join(lines))

    print(f"Converted {src_png} ({len(raw_data)} B -> {len(clean_data)} B) -> {out_header}")

if __name__ == "__main__":
    main()
